const THAI_PROVINCES = [
  { code: "10", nameThai: "กรุงเทพมหานคร", nameEnglish: "Bangkok" },
  { code: "11", nameThai: "อ่างทอง", nameEnglish: "Ang Thong" },
  { code: "12", nameThai: "อุตรดิตถ์", nameEnglish: "Uthai Thani" },
  { code: "13", nameThai: "กำแพงเพชร", nameEnglish: "Kamphaeng Phet" },
  { code: "14", nameThai: "นครสวรรค์", nameEnglish: "Nakhon Sawan" },
  { code: "15", nameThai: "เพชรบูรณ์", nameEnglish: "Phetchabun" },
  { code: "16", nameThai: "พิษณุโลก", nameEnglish: "Phitsanulok" },
  { code: "17", nameThai: "สุโขทัย", nameEnglish: "Sukhothai" },
  { code: "18", nameThai: "ตาก", nameEnglish: "Tak" },
  { code: "19", nameThai: "เพชรบูรี", nameEnglish: "Phetchaburi" },
  { code: "20", nameThai: "เชียงใหม่", nameEnglish: "Chiang Mai" },
  { code: "21", nameThai: "เชียงราย", nameEnglish: "Chiang Rai" },
  { code: "22", nameThai: "น่าน", nameEnglish: "Nan" },
  { code: "23", nameThai: "พะเยา", nameEnglish: "Phayao" },
  { code: "24", nameThai: "แพร่", nameEnglish: "Phrae" },
  { code: "25", nameThai: "ลำปาง", nameEnglish: "Lampang" },
  { code: "26", nameThai: "ลำพูน", nameEnglish: "Lamphun" },
  { code: "27", nameThai: "แม่ฮ่องสอน", nameEnglish: "Mae Hong Son" },
  { code: "30", nameThai: "อำนาจเจริญ", nameEnglish: "Amnat Charoen" },
  { code: "31", nameThai: "บึงกาฬ", nameEnglish: "Bueng Kan" },
  { code: "32", nameThai: "นครพนม", nameEnglish: "Nakhon Phanom" },
  { code: "33", nameThai: "หนองคาย", nameEnglish: "Nong Khai" },
  { code: "34", nameThai: "อุดรธานี", nameEnglish: "Udon Thani" },
  { code: "35", nameThai: "เลย", nameEnglish: "Loei" },
  { code: "36", nameThai: "มหาสารคาม", nameEnglish: "Maha Sarakham" },
  { code: "37", nameThai: "ขอนแก่น", nameEnglish: "Khon Kaen" },
  { code: "38", nameThai: "สูรินทร์", nameEnglish: "Surin" },
  { code: "39", nameThai: "นครราชสีมา", nameEnglish: "Nakhon Ratchasima" },
  { code: "40", nameThai: "นครศรีธรรมราช", nameEnglish: "Nakhon Si Thammarat" },
  { code: "41", nameThai: "กาญจนบุรี", nameEnglish: "Kanchanaburi" },
  { code: "42", nameThai: "ราชบุรี", nameEnglish: "Ratchaburi" },
  { code: "43", nameThai: "สมุทรสาคร", nameEnglish: "Samut Sakhon" },
  { code: "44", nameThai: "สมุทรสงคราม", nameEnglish: "Samut Songkhram" },
  { code: "45", nameThai: "สระแก้ว", nameEnglish: "Sa Kaew" },
  { code: "46", nameThai: "สระบุรี", nameEnglish: "Saraburi" },
  { code: "47", nameThai: "สิงห์บุรี", nameEnglish: "Sing Buri" },
  { code: "48", nameThai: "ปทุมธานี", nameEnglish: "Pathum Thani" },
  { code: "49", nameThai: "พระนครศรีอยุธยา", nameEnglish: "Phra Nakhon Si Ayutthaya" },
  { code: "50", nameThai: "ชลบุรี", nameEnglish: "Chon Buri" },
  { code: "51", nameThai: "จันทบุรี", nameEnglish: "Chanthaburi" },
  { code: "52", nameThai: "ตราด", nameEnglish: "Trat" },
  { code: "53", nameThai: "นนทบุรี", nameEnglish: "Nonthaburi" },
  { code: "54", nameThai: "นครปฐม", nameEnglish: "Nakhon Pathom" },
  { code: "55", nameThai: "สุพรรณบุรี", nameEnglish: "Suphan Buri" },
  { code: "56", nameThai: "ลำลูกกา", nameEnglish: "Lam Luk Ka" },
  { code: "57", nameThai: "สระหลวง", nameEnglish: "Sara Buri" },
  { code: "58", nameThai: "นครนายก", nameEnglish: "Nakhon Nayok" },
  { code: "59", nameThai: "ประจวบคีรีขันธ์", nameEnglish: "Prachuap Khiri Khan" },
  { code: "60", nameThai: "ชัยนาท", nameEnglish: "Chainat" },
  { code: "61", nameThai: "พังงา", nameEnglish: "Phang-nga" },
  { code: "62", nameThai: "ภูเก็ต", nameEnglish: "Phuket" },
  { code: "63", nameThai: "สุราษฎร์ธานี", nameEnglish: "Surat Thani" },
  { code: "64", nameThai: "สตูล", nameEnglish: "Satun" },
  { code: "65", nameThai: "ตรัง", nameEnglish: "Trang" },
  { code: "66", nameThai: "สงขลา", nameEnglish: "Songkhla" },
  { code: "67", nameThai: "สมุทรปราการ", nameEnglish: "Samut Prakan" },
  { code: "68", nameThai: "กระบี่", nameEnglish: "Krabi" },
  { code: "69", nameThai: "พัทลุง", nameEnglish: "Phatthalung" },
  { code: "70", nameThai: "ปัตตานี", nameEnglish: "Pattani" },
  { code: "71", nameThai: "ยะลา", nameEnglish: "Yala" },
  { code: "72", nameThai: "นราธิวาส", nameEnglish: "Narathiwat" },
  { code: "73", nameThai: "ลพบุรี", nameEnglish: "Lopburi" },
  { code: "74", nameThai: "ปราจีนบุรี", nameEnglish: "Prachuap Khiri Khan" },
  { code: "75", nameThai: "ศรีสะเกษ", nameEnglish: "Sisaket" },
  { code: "76", nameThai: "ชัยภูมิ", nameEnglish: "Chaiyaphum" },
  { code: "77", nameThai: "ยโสธร", nameEnglish: "Yasothon" },
  { code: "78", nameThai: "ร้อยเอ็ด", nameEnglish: "Roi Et" },
  { code: "79", nameThai: "กาฬสินธุ์", nameEnglish: "Kalasin" },
  { code: "80", nameThai: "สกลนคร", nameEnglish: "Sakon Nakhon" },
  { code: "81", nameThai: "มุกดาหาร", nameEnglish: "Mukdahan" },
  { code: "82", nameThai: "อุบลราชธานี", nameEnglish: "Ubon Ratchathani" },
  { code: "83", nameThai: "หนองบัวลำภู", nameEnglish: "Nong Bua Lam Phu" },
  { code: "84", nameThai: "พิจิตร", nameEnglish: "Phichit" },
  { code: "85", nameThai: "นครศรีธรรมราช", nameEnglish: "Nakhon Luang Thammarat" },
  { code: "86", nameThai: "ยโสธร", nameEnglish: "Yasothon Province" }
];
